### ISSUE TITLE
Vovcha: Does the "Cho-Yang" cargo container still exist?

### ISSUE THREAD

**Issue by amykyta3** [amykyta3/plast-karto#11]
Now that Чорноморці have moved their boat storage to ПК, does the storage container still exist? Has it been moved?

Photo is from 2017:
![image](https://user-images.githubusercontent.com/12021539/83335820-44a03200-a264-11ea-8d30-7b61fca01f2a.png)

**Comment by MKucy** [comment]
Still there
![image](https://user-images.githubusercontent.com/109386593/179298743-b0684bcd-9aa3-4bd6-8ebe-4e6b2eb57247.jpg)

**Comment by amykyta3** [comment]
Thanks!!
